import test from 'node:test';import assert from'node:assert/strict';
globalThis.__VL__={};for(const f of ['retry-policy.js','scheduler.js','auto-engine.js'])await import(`../src/core/${f}`).catch(()=>{});await import('../src/rover/conflicts.js').catch(()=>{});const VL=globalThis.__VL__;
const result={primera:'45',segunda:'63',tercera:'91',pick3:'245',pick4:'6391'};
function harness({enabled=true,sourceResult=result,snap={found:true,processed:false,rawCode:'BRAZIL03PM ',values:{primera:'',segunda:'',tercera:'',pick3:'---',pick4:'---'},duplicates:[]},verify={state:'DONE'}}={}){let publish=0,sourceCalls=0;let settingsOn=enabled;const states=new Map();const registry={brazil:{automationSupported:true,source:'qplay',draws:{BRAZIL03PM:{time:'15:00',hora:'03:00 PM'}}}};const settingsStore={resolve:()=>({effectiveEnabled:settingsOn,time:'15:00',retryPolicy:{offsets:[1,3,5],afterLast:30},lottery:registry.brazil,draw:registry.brazil.draws.BRAZIL03PM})};const stateStore={get:(d,c)=>states.get(`${d}|${c}`)||null,patch:(d,c,p)=>{const k=`${d}|${c}`,n={...(states.get(k)||{dateIso:d,state:'WAITING_TIME'}),...p};states.set(k,n);return n}};let resolveSource;const sourcePromise=sourceResult==='DEFER'?new Promise(r=>resolveSource=r):null;const sourceAdapters={qplay:{fetchResult:async()=>{sourceCalls++;return sourcePromise||sourceResult}}};const roverReader={read:async()=>snap};const roverProcessor={process:async()=>{publish++;return{httpOk:true,text:'x'}}};const verifier=async()=>verify;const clock=()=>({dateIso:'2026-09-28',dateUs:'09/28/2026',minuteOfDay:918,second:0});const engine=VL.createAutoEngine({registry,settingsStore,stateStore,sourceAdapters,roverReader,roverProcessor,verifier,clock,logger:{log(){},warn(){},error(){}}});return{engine,states,get publish(){return publish},get sourceCalls(){return sourceCalls},setEnabled:v=>settingsOn=v,resolveSource};}

test('Master/lottery/draw OFF starts no work',async()=>{const h=harness({enabled:false});await h.engine.evaluateDraw('brazil','BRAZIL03PM');assert.equal(h.sourceCalls,0);assert.equal(h.publish,0)});
test('processed exact is DONE without POST',async()=>{const h=harness({snap:{found:true,processed:true,rawCode:'BRAZIL03PM ',values:result,duplicates:[]}});await h.engine.evaluateDraw('brazil','BRAZIL03PM');assert.equal(h.publish,0);assert.equal(h.states.get('2026-09-28|BRAZIL03PM').state,'DONE')});
test('conflict and duplicate stop without POST',async()=>{const c=harness({snap:{found:true,processed:false,rawCode:'BRAZIL03PM ',values:{...result,primera:'44'},duplicates:[]}});await c.engine.evaluateDraw('brazil','BRAZIL03PM');assert.equal(c.publish,0);assert.equal(c.states.get('2026-09-28|BRAZIL03PM').state,'CONFLICT');const d=harness({snap:{found:true,processed:false,rawCode:'BRAZIL03PM ',values:{primera:'',segunda:'',tercera:'',pick3:'',pick4:''},duplicates:[{code:'X',name:'X'}]}});await d.engine.evaluateDraw('brazil','BRAZIL03PM');assert.equal(d.publish,0);assert.equal(d.states.get('2026-09-28|BRAZIL03PM').state,'DUPLICATE')});
test('safe pending row publishes once then verifier decides',async()=>{const h=harness();await h.engine.evaluateDraw('brazil','BRAZIL03PM');assert.equal(h.publish,1);assert.equal(h.states.get('2026-09-28|BRAZIL03PM').state,'DONE');await h.engine.evaluateDraw('brazil','BRAZIL03PM');assert.equal(h.publish,1)});
test('missing Rover row is recoverable ERROR with zero POST',async()=>{const h=harness({snap:{found:false}});await h.engine.evaluateDraw('brazil','BRAZIL03PM');assert.equal(h.publish,0);assert.equal(h.states.get('2026-09-28|BRAZIL03PM').lastError,'ROVER_ROW_NOT_FOUND')});
test('switch OFF while source is in flight prevents publish',async()=>{const h=harness({sourceResult:'DEFER'});const p=h.engine.evaluateDraw('brazil','BRAZIL03PM');h.setEnabled(false);h.resolveSource(result);await p;assert.equal(h.publish,0)});
test('PROCESS_UNCERTAIN never blindly republishes',async()=>{const h=harness({verify:{state:'PROCESS_UNCERTAIN'}});await h.engine.evaluateDraw('brazil','BRAZIL03PM');assert.equal(h.publish,1);await h.engine.evaluateDraw('brazil','BRAZIL03PM');assert.equal(h.publish,1)});
