import test from 'node:test'; import assert from 'node:assert/strict'; import {readFile} from 'node:fs/promises';
globalThis.__VL__={}; for(const f of ['conflicts.js','reader.js','processor.js','verifier.js']) await import(`../src/rover/${f}`).catch(()=>{}); const VL=globalThis.__VL__;
const processed=await readFile(new URL('./fixtures/rover/brazil-processed.html',import.meta.url),'utf8'); const pending=await readFile(new URL('./fixtures/rover/brazil-pending.html',import.meta.url),'utf8');
const r3={primera:'45',segunda:'63',tercera:'91',pick3:'245',pick4:'6391'};
test('normalization/conflict/exact helpers',()=>{assert.equal(VL.normalizeRoverValue('---'),'');assert.equal(VL.hasConflict({...r3,primera:'44'},r3),true);assert.equal(VL.hasConflict({...r3,pick3:'---'},r3),false);assert.equal(VL.isExactMatch(r3,r3),true)});
test('reader matches normalized code but preserves raw Rover code',async()=>{let body='';const fetchFn=async(_u,o)=>{body=o.body;return{ok:true,status:200,text:async()=>processed}};const snap=await VL.createRoverReader({fetchFn}).read({dateUs:'09/27/2026',drawCode:'BRAZIL03PM',result:r3});assert.equal(snap.found,true);assert.equal(snap.rawCode,'BRAZIL03PM ');assert.equal(snap.processed,true);assert.deepEqual(snap.values,r3);assert.match(body,/fecha=09%2F27%2F2026/);assert.equal('html' in snap,false)});
test('all four observed Brazil values parse exactly',()=>{const rows=VL.parseRoverRows(processed);const expected={BRAZIL12PM:['59','67','29','859','6729'],BRAZIL03PM:['45','63','91','245','6391'],BRAZIL07PM:['68','95','25','868','9525'],BRAZIL08PM:['26','74','96','926','7496']};for(const [code,v] of Object.entries(expected)){const row=rows.find(x=>x.code===code);assert.deepEqual(Object.values(row.values),v)}});
test('reader reports missing row without fabricating success',async()=>{const fetchFn=async()=>({ok:true,status:200,text:async()=>pending});const snap=await VL.createRoverReader({fetchFn}).read({dateUs:'09/27/2026',drawCode:'BRAZIL12PM'});assert.deepEqual(snap,{found:false})});
test('processor uses ISO date and exact raw code',async()=>{let body='';const fetchFn=async(_u,o)=>{body=o.body;return{ok:true,status:200,text:async()=> 'RESULTADOS PROCESADOS'}};const out=await VL.createRoverProcessor({fetchFn}).process({dateIso:'2026-09-27',rawCode:'BRAZIL03PM ',result:r3});assert.equal(out.httpOk,true);assert.match(body,/fecha=2026-09-27/);assert.match(body,/loteria=BRAZIL03PM\+/)});
