import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';
globalThis.__VL__={};for(const f of ['http.js','qplay.js','queen.js','premier.js','rapid.js','nationjl.js','extra.js','index.js'])await import(`../src/sources/${f}`).catch(()=>{});const VL=globalThis.__VL__;
const qhtml=await readFile(new URL('./fixtures/sources/qplay.html',import.meta.url),'utf8');const qnhtml=await readFile(new URL('./fixtures/sources/queen.html',import.meta.url),'utf8');
test('QPlay parses exact Brazil 3PM result and rejects malformed lengths',()=>{assert.deepEqual(VL.parseQPlay(qhtml)[0],{fecha:'09/27/2026',hora:'03:00 PM',primera:'45',segunda:'63',tercera:'91',pick3:'245',pick4:'6391'});assert.deepEqual(VL.parseQPlay(qhtml.replace('/img/pick4.png','/img/pick4x.png')),[])});
test('Queen preserves leading zeroes in picks',()=>{const r=VL.parseQueen(qnhtml)[0];assert.equal(r.primera,'98');assert.equal(r.pick3,'098');assert.equal(r.pick4,'2036');assert.equal(r.queenKey,'QL MORNING')});
test('Premier parser and request headers stay compatible',async()=>{const p=VL.parsePremier({results:[{date:'2026-09-27',sortition:{abbreviation:'3PM'},first:45,second:63,third:91,cashThree:245,pickFour:6391}]})[0];assert.equal(p.fecha,'09/27/2026');let seen;await VL.createPremierSource({request:async(url,headers)=>{seen={url,headers};return JSON.stringify({results:[]})}}).fetchResult({draw:{premierKey:'3PM'},dateUs:'09/27/2026'});assert.equal(seen.headers.Origin,'https://premierlotto.tv');assert.equal(seen.headers.Referer,'https://premierlotto.tv/');assert.equal(seen.headers.Accept,'application/json')});
test('Rapid pending remains pending',async()=>{const src=VL.createRapidSource({request:async()=>JSON.stringify({draws:[{time:'15:00',completed:0}],history:[]}),todayUs:()=> '09/28/2026'});assert.deepEqual(await src.fetchResult({draw:{hora24:'15:00',hora:'03:00 PM'},dateUs:'09/28/2026'}),{pending:true})});
test('EXTRA maps 7 digits to only three awards',()=>{const html='<div class="resultsdrawing"><time datetime="2026-09-28T12:00:00"></time><ul class="resultsnums"><li>1</li><li>2</li><li>3</li><li>4</li><li>5</li><li>6</li><li>7</li></ul></div>';assert.deepEqual(VL.parseExtra(html,'2026-09-28'),{fecha:'09/28/2026',numero:'1234567',primera:'67',segunda:'23',tercera:'45'})});
test('EXTRA rejects a canonical URL that is not Quebec Extra',()=>{const html='<link rel="canonical" href="https://www.lotterypost.com/results/ny/pick3"><div class="resultsdrawing"><time datetime="2026-09-28T12:00:00"></time><ul class="resultsnums"><li>1</li><li>2</li><li>3</li><li>4</li><li>5</li><li>6</li><li>7</li></ul></div>';assert.throws(()=>VL.parseExtra(html,'2026-09-28'),/no corresponde a Québec Extra/)});
