(function(VL){'use strict';
 const REINJECTION_DEBOUNCE_MS=450;const ICON_SEARCH='🔎',ICON_OK='✓',ICON_ERR='×';
 function findLotteryInput(root,code){return [...root.querySelectorAll('input[loteria]')].find(i=>String(i.getAttribute('loteria')||'').trim()===code)||null}
 function manualFieldsForSource(source){return source==='extra'?['primera','segunda','tercera']:['primera','segunda','tercera','pick3','pick4']}
 function roverDate(root){const v=String(root.querySelector('#fecha')?.value||'').trim();return /^\d{2}\/\d{2}\/\d{4}$/.test(v)?v:''}
 function writeInput(input,value){input.value=String(value);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}
 function createManualController({root=document,registry,sourceAdapters,logger=console}){let revision=0;let timer=null;const requests=new WeakMap();
  function entries(){const out=[];for(const lotteryId of Object.keys(registry)){const l=registry[lotteryId];for(const code of Object.keys(l.draws))out.push({code,lottery:l,draw:l.draws[code]})}return out}
  async function search(code,tr,btn){const info=entries().find(x=>x.code===code),date=roverDate(root);if(!info||!date)return;const rev=revision,token=Symbol();requests.set(btn,token);btn.disabled=true;btn.textContent='…';try{const result=await sourceAdapters[info.lottery.source].fetchResult({draw:info.draw,dateUs:date});if(requests.get(btn)!==token||rev!==revision||date!==roverDate(root)||!tr.isConnected)return;if(result?.pending||!result){btn.disabled=false;btn.textContent=ICON_ERR;setTimeout(()=>{btn.textContent=ICON_SEARCH},2000);return}const fields=manualFieldsForSource(info.lottery.source);for(const f of fields){if(typeof result[f]!=='string'||result[f]==='')throw new Error('Resultado incompleto');const input=tr.querySelector(`input[name="${f}"]`);if(!input)throw new Error(`Input ${f} no encontrado`);writeInput(input,result[f]);input.classList?.add('rs-source-filled')}btn.disabled=false;btn.textContent=ICON_OK}catch(e){logger.error?.('[Fuentes]',e);btn.disabled=false;btn.textContent=ICON_ERR}}
  function installButtons(){let added=0;for(const info of entries()){const input=findLotteryInput(root,info.code);if(!input)continue;const tr=input.closest('tr');if(!tr||tr.querySelector(`.rs-source-fetch-btn[data-codigo="${info.code}"]`))continue;const ab=tr.querySelector('.loteria-abrev');if(!ab)continue;const b=root.createElement('button');b.type='button';b.className='rs-source-fetch-btn';b.dataset.codigo=info.code;b.textContent=ICON_SEARCH;b.title=`Buscar en ${info.lottery.name}`;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(!b.disabled)search(info.code,tr,b)});ab.insertAdjacentElement('afterend',b);added++}return added}
  function installDateListener(){const f=root.querySelector('#fecha');if(!f||f.dataset.rsSourcesListenerInstalled)return false;f.dataset.rsSourcesListenerInstalled='1';const reset=()=>{revision++;sourceAdapters.extra?.cancelAll?.();root.querySelectorAll('.rs-source-fetch-btn').forEach(b=>{b.disabled=false;b.textContent=ICON_SEARCH})};f.addEventListener('change',reset);f.addEventListener('input',reset);return true}
  function needsReinjection(){if(root.querySelector('#resultadosLoteria')&&!root.querySelector('#vl-auto-toolbar'))return true;const f=root.querySelector('#fecha');if(f&&!f.dataset.rsSourcesListenerInstalled)return true;for(const info of entries()){const input=findLotteryInput(root,info.code);if(!input)continue;const tr=input.closest('tr');if(tr&&!tr.querySelector(`.rs-source-fetch-btn[data-codigo="${info.code}"]`))return true}return false}
  function scheduleReinjection(fn){clearTimeout(timer);timer=setTimeout(()=>{timer=null;if(needsReinjection())fn()},REINJECTION_DEBOUNCE_MS)}
  return{installButtons,installDateListener,needsReinjection,scheduleReinjection,search};
 }
 Object.assign(VL,{REINJECTION_DEBOUNCE_MS,findLotteryInput,manualFieldsForSource,createManualController});
})(globalThis.__VL__ ||= {});
