const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const script = fs.readFileSync(path.join(root, 'Rovs-Loterias-USA.user.js'), 'utf8');
const meta = fs.readFileSync(path.join(root, 'Rovs-Loterias-USA.meta.js'), 'utf8');
const end = '// ==/UserScript==';
const header = script.slice(0, script.indexOf(end) + end.length) + '\n';
const get = key => header.match(new RegExp(`^// @${key}\\s+(.+)$`, 'm'))?.[1];
assert.equal(meta, header, 'La cabecera de actualización debe coincidir con el script');
assert.match(get('version'), /^\d+\.\d+\.\d+$/);
assert.equal(get('name'), 'Rovs Loterías USA', 'El nombre debe ser estable y no incluir una versión');
assert.equal(get('namespace'), 'http://tampermonkey.net/');
const base = 'https://raw.githubusercontent.com/Nox1do/rover-lottery/main/Loterias%20USA/';
assert.equal(get('updateURL'), base + 'Rovs-Loterias-USA.meta.js');
assert.equal(get('downloadURL'), base + 'Rovs-Loterias-USA.user.js');
assert.equal(fs.readFileSync(path.join(root, 'versions', `Rovs-Loterias-USA-v${get('version')}.user.js`), 'utf8'), script);
new vm.Script(script);
console.log(`Publicación v${get('version')} OK: identidad, URLs, metadatos, historial y sintaxis`);
