(function(VL){'use strict';
 const EXTRA_URL='https://www.lotterypost.com/results/qc/extra/past',WAIT=120000;
 function parseExtra(html,dateIso){if(/just a moment|attention required/i.test(html))throw new Error('Lottery Post: verificación Cloudflare; no se obtuvieron resultados');const canonical=String(html).match(/<link\b[^>]*rel=["']canonical["'][^>]*href=["']([^"']+)["']/i)?.[1]||String(html).match(/<link\b[^>]*href=["']([^"']+)["'][^>]*rel=["']canonical["']/i)?.[1];if(canonical){const u=new globalThis.URL(canonical,EXTRA_URL);if(u.hostname!=='www.lotterypost.com'||!/^\/results\/qc\/extra(?:\/|$)/.test(u.pathname))throw new Error('Lottery Post: la respuesta no corresponde a Québec Extra');}const blocks=[...String(html).matchAll(/<[^>]*class=["'][^"']*resultsdrawing[^"']*["'][^>]*>([\s\S]*?)(?=<[^>]*class=["'][^"']*resultsdrawing|$)/gi)].map(m=>m[1]);const matches=blocks.filter(b=>new RegExp(`datetime=["']${dateIso}T`).test(b));if(!matches.length)return null;if(matches.length!==1)throw new Error('Lottery Post: más de un sorteo para la misma fecha');const list=matches[0].match(/class=["'][^"']*resultsnums[^"']*["'][^>]*>([\s\S]*?)<\/ul>/i)?.[1]||'';const digits=[...list.matchAll(/<li[^>]*>\s*(\d)\s*<\/li>/gi)].map(m=>m[1]);if(digits.length!==7)return null;const n=digits.join('');return{fecha:`${dateIso.slice(5,7)}/${dateIso.slice(8,10)}/${dateIso.slice(0,4)}`,numero:n,primera:n.slice(5,7),segunda:n.slice(1,3),tercera:n.slice(3,5)}}
 function dateIsoFromUs(us){const m=String(us).match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?`${m[3]}-${m[1]}-${m[2]}`:''}
 function createExtraSource({api=globalThis,cryptoObj=globalThis.crypto}={}){const cancels=new Set();function cancelAll(){for(const f of [...cancels])f()}
  function fetchResult({dateUs}){const dateIso=dateIsoFromUs(dateUs);if(!dateIso)return Promise.reject(new Error('Extra: fecha inválida'));return new Promise((resolve,reject)=>{const id=cryptoObj.randomUUID(),rk=`vl-extra-request:${id}`,sk=`vl-extra-response:${id}`;let done=false,listener,timer,tab;const finish=(err,res,close=false)=>{if(done)return;done=true;clearTimeout(timer);if(listener!==undefined)api.GM_removeValueChangeListener(listener);api.GM_deleteValue(rk);api.GM_deleteValue(sk);cancels.delete(cancel);if(close&&tab)tab.close();err?reject(err):resolve(res)};const cancel=()=>finish(new Error('Extra: consulta cancelada por cambio de fecha'),null,true);cancels.add(cancel);listener=api.GM_addValueChangeListener(sk,(_k,_o,r)=>{if(!r||r.id!==id||r.fechaISO!==dateIso)return;if(r.error)return finish(new Error(r.error));if(r.numero===null)return finish(null,null,true);if(!/^\d{7}$/.test(r.numero||''))return finish(new Error('Extra: resultado inválido recibido de la pestaña'));const n=r.numero;finish(null,{fecha:dateUs,numero:n,primera:n.slice(5,7),segunda:n.slice(1,3),tercera:n.slice(3,5)},true)});api.GM_setValue(rk,{id,fechaISO:dateIso,creada:Date.now()});timer=setTimeout(()=>finish(new Error('Extra: tiempo de espera de 2 minutos agotado.'),null,true),WAIT);const [y,m]=dateIso.split('-');tab=api.GM_openInTab(`${EXTRA_URL}/${y}/${Number(m)}#${new URLSearchParams({vlExtra:id})}`,{active:false,insert:true,setParent:true});if(!tab)finish(new Error('Extra: no se pudo abrir la pestaña de Lottery Post'))})}
  return{fetchResult,cancelAll};}
 function handleExtraTab({api=globalThis,doc=globalThis.document,loc=globalThis.location}={}){const id=new URLSearchParams(loc.hash.slice(1)).get('vlExtra');if(!id||!/^[a-f0-9-]{36}$/i.test(id))return false;const rk=`vl-extra-request:${id}`,req=api.GM_getValue(rk,null);if(!req||req.id!==id||!/^\d{4}-\d{2}-\d{2}$/.test(req.fechaISO)||Date.now()-req.creada>WAIT)return false;let done=false,obs,timer;const stop=()=>{done=true;obs?.disconnect();clearTimeout(timer)};const read=()=>{if(done)return;const cur=api.GM_getValue(rk,null);if(!cur||cur.id!==id)return stop();if(!doc.querySelector('.resultsdrawing'))return;let response;try{const r=parseExtra(doc.documentElement.outerHTML,req.fechaISO);response={id,fechaISO:req.fechaISO,numero:r?.numero??null}}catch(e){response={id,fechaISO:req.fechaISO,error:e.message}}stop();api.GM_setValue(`vl-extra-response:${id}`,response)};obs=new MutationObserver(read);obs.observe(doc.documentElement,{childList:true,subtree:true});timer=setTimeout(stop,Math.max(0,WAIT-(Date.now()-req.creada)));read();return true}
 Object.assign(VL,{EXTRA_URL,EXTRA_WAIT_MS:WAIT,parseExtra,createExtraSource,handleExtraTab});
})(globalThis.__VL__ ||= {});
